name-template: 'Energy Bridge v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐞 Fixes'
    labels: ['bug', 'fix']
  - title: '🧹 Chore'
    labels: ['chore', 'build', 'ci', 'docs']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What’s Changed
  $CHANGES

  ## Full Changelog
  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$NEXT_TAG
version-resolver:
  major:
    labels: ['semver:major']
  minor:
    labels: ['semver:minor', 'feature']
  patch:
    labels: ['semver:patch', 'bug', 'fix', 'chore']
  default: patch
