name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

# 👇 Add this block
permissions:
  contents: write   # needed to create GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build
      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: energybridge-jar
          path: build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    # (Optional) You can set permissions here instead of top-level:
    # permissions:
    #   contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: energybridge-jar
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.jar
          generate_release_notes: true
          # (Optional) be explicit about token; usually not needed:
          # token: ${{ secrets.GITHUB_TOKEN }}
